/**
 * 养老服务数据管理服务
 * 完全按照v0工程设计，3个服务类型拥有不同的section结构
 */

import { Caregiver, ServicePackage, QualificationDetail, FAQItem, ServiceType } from '@/types/elderly';

// ============= 长者照顾服务 (elderly-care) =============

export const elderlyWhyNeed = {
  title: '为什么需要长者照顾服务？',
  content:
    '照顾老人家的工作不容易，如果需要同时兼顾其他工作，压力大之余亦难免会分身不暇。家中长者年纪渐大，身体机能或会下降减弱，如果出现失禁、无法自理、记忆力衰退等情况，就需要聘请专业的长者起居照顾员/护理员/保健员，上门为老人家提供专业的长者护理服务。',
  situations: ['失禁、无法自理', '记忆力衰退', '需要医疗护理', '独居长者', '术后康复', '慢性病管理'],
};

// ============= 陪诊服务 (escort) =============

export const escortWhyNeed = {
  title: '什么是陪诊服务？',
  content: '专业陪诊员提供护送陪诊服务，由曾接受护理训练的合资格护理员/保健员提供',
  additionalInfo: '陪诊人员除了协助护送患者或长者覆诊及取药外，亦会仔细聆听医生囑咐，纪录病情并向家人匯报情况。',
};

export const escortServiceDetails = {
  description: '专业陪诊员提供护送陪诊服务，由曾接受护理训练的合资格护理员/保健员提供',
  services: [
    '扶抱行动不便客户上落轮椅',
    '安排外出交通',
    '协助客户检查前更衣换鞋',
    '与医护人员沟通',
    '取药及办理各类手续',
    '监察客户身体状况',
    '仔细聆听医生囑咐',
    '纪录病情并向家人匯报',
  ],
  pricing: '¥80-150/小时，一般3-4小时/次',
  suitableFor: ['长期病患者', '年长者', '腦退化症患者', '行动不便人士', '需要医疗翻译的患者'],
};

export const escortWhyNeedDetails = {
  sections: [
    {
      title: '专业知识',
      content:
        '陪诊员不只是陪病人去医院那么简单，当中需要的专业知识很多。陪诊员担任客户在外的照顾者，走在街上，万一遇上突发情况，手边又没有太多医疗设备可以协助处理，陪诊员需要靠自身的专业知识作出即时判断，评估客户状况，采取适当行动。',
    },
    {
      title: '经验',
      content:
        '作为合格陪诊员须接受相关训练，学习处理伤口、急救知识、扶抱技巧、使用轮椅及助行架等。部分公司会要求陪诊员持有护理员或保健员证书，确保服务质量。',
    },
    {
      title: '责任',
      content:
        '陪诊员需要全程照顾客户，包括协助更衣、如厕、用餐等日常起居，同时要留意客户的身体状况，如有不适要及时通知医护人员。陪诊员还需要详细记录医生的诊断和处方，向家属清晰汇报。',
    },
  ],
};

// ============= 医护替补 (medical-staff) =============

export const medicalStaffWhyNeed = {
  title: '什么时候需要医护人员替补？',
  content:
    '当医院或老人院等医疗机构需要人手支援时，尤其遇上流感爆发、季节性需求、突发事故、正规医护人员放假、职位空缺等情况，便可以向护理中介公司聘请替假护士、替假保健员、替假护理员等医护人员，即时解决医护人手需求。',
  situations: ['流感爆发', '季节性需求', '突发事故', '人员放假', '职位空缺', '临时增援'],
};

export const medicalStaffDetails = {
  description: '为医院、老人院、学校等医疗机构提供专业医护人员替补方案',
  staffTypes: [
    {
      type: '注册/登记护士 (RN/EN)',
      services: ['洗肚（腹膜透析）', '洗胃', '插尿喉', '插胃喉', '派药', '量度体溫和血壓'],
      pricing: '约¥1,400-2,000/更（8-12小时）',
    },
    {
      type: '保健员/护理员 (HW/PCW)',
      services: ['协助客户沐浴更衣', '陪同覆诊', '扶抱及转位', '量度生命体征', '更换尿片', '协助进食及用药提醒'],
      pricing: '约¥800-1,400/更（8-12小时）',
    },
    {
      type: '治疗师助理 (PT/OT/ST助理)',
      services: ['协助物理治疗', '协助职业治疗', '协助言语治疗', '康复训练辅助'],
      pricing: '约¥1,000-1,600/更（8-12小时）',
    },
  ],
  suitableOrganizations: ['公私营医院', '护理中心', '诊所', '安老院舍', '学校', '康复中心', '体检中心', '社区中心'],
  process: [
    { step: 1, title: '提出需求', desc: '机构提出人手需求，说明所需资质、时间和人数' },
    { step: 2, title: '快速配对', desc: '24小时内为机构配对合适的医护人员' },
    { step: 3, title: '确认安排', desc: '双方确认服务时间、价格和具体要求' },
    { step: 4, title: '开始服务', desc: '医护人员按时到岗，提供专业替补服务' },
  ],
};

// ============= 共同数据 =============

// 资质详情说明（仅用于长者照顾服务）
export const qualificationDetails: QualificationDetail[] = [
  {
    id: 'pcw',
    title: '护理员 (PCW)',
    subtitle: '基本起居照顾服务',
    price: '60-80元/小时',
    description: '持有护理员证书，提供日常生活照护服务',
    services: ['协助长者如厕/沐浴', '陪诊服务', '更换尿片', '出入扶抱', '老人膳食照顾', '陪伴长者外出', '用药提醒', '日常清洁'],
    requirements: '持有社会福利署认可的护理员证书',
  },
  {
    id: 'hw',
    title: '保健员 (HW)',
    subtitle: '医护相关护理服务',
    price: '100-120元/小时',
    description: '持有保健员注册证，可提供基础医护服务',
    services: ['所有护理员服务', '伤口护理', '处理尿袋或便袋', '鼻/胃管喂食', '血压血糖监测', '简单物理治疗', '康复训练辅助', '慢病管理'],
    requirements: '持有社会福利署认可的保健员注册证及相关培训证书',
    badge: 'HW',
  },
  {
    id: 'rn',
    title: '注册护士 (RN) / 登记护士 (EN)',
    subtitle: '专业医疗护理服务',
    price: '150-250元/小时',
    description: '持有护士管理局执业证明书，提供专业医疗服务',
    services: ['所有保健员服务', '药物注射', '洗肚（腹膜透析）', '抽血', '换药', '导尿管护理', '造口护理', '专业健康评估'],
    requirements: '持有香港护士管理局发出的执业证明书',
    badge: 'RN/EN',
  },
];

// 服务套餐（共用）
export const servicePackages: ServicePackage[] = [
  {
    id: 'hourly',
    name: '按小时服务',
    description: '灵活安排，按需预约',
    prices: [
      { type: 'PCW', price: 80, unit: '/小时' },
      { type: 'HW', price: 120, unit: '/小时' },
      { type: 'RN', price: 200, unit: '/小时' },
    ],
    features: ['最少2小时起', '提前1天预约', '可选时段8:00-23:00', '灵活调整时间'],
    popular: false,
    note: '适合短期临时需求',
  },
  {
    id: 'daily',
    name: '按天服务',
    description: '全天照护，专人负责',
    prices: [
      { type: 'PCW', price: 640, unit: '/天' },
      { type: 'HW', price: 960, unit: '/天' },
      { type: 'RN', price: 1600, unit: '/天' },
    ],
    features: ['8-12小时服务', '提前3天预约', '固定护理员', '每日服务报告'],
    popular: true,
    note: '适合术后康复、短期照护',
  },
  {
    id: '24hour',
    name: '24小时服务',
    description: '全天候专业照护',
    prices: [
      { type: 'PCW', price: 1280, unit: '/天', save: '省¥640' },
      { type: 'HW', price: 1920, unit: '/天', save: '省¥960' },
      { type: 'RN', price: 3200, unit: '/天', save: '省¥1600' },
    ],
    features: ['24小时贴身照护', '2-3名护理员轮班', '全天健康监测', '紧急情况快速响应'],
    popular: false,
    note: '适合重症护理、术后恢复',
  },
  {
    id: 'monthly',
    name: '包月服务',
    description: '长期照护，优惠更多',
    prices: [
      { type: 'PCW', price: 15000, unit: '/月', save: '省15%' },
      { type: 'HW', price: 22000, unit: '/月', save: '省15%' },
      { type: 'RN', price: 48000, unit: '/月', save: '省20%' },
    ],
    features: ['全月服务', '专属护理员', '定期健康评估', '家属定期沟通'],
    popular: false,
    note: '适合长期照护需求',
    discount: '比按天服务节省15-20%',
  },
];

// FAQ（按服务类型分类）
export const faqsByServiceType: Record<ServiceType, FAQItem[]> = {
  'elderly-care': [
    {
      question: '为什么需要聘请养老护理服务？',
      answer:
        '照顾老人家的工作不容易，如果需要同时兼顾其他工作，压力大之餘亦难免会分身不暇。如果家中长者年纪渐大，身体机能下降，出现失禁、无法自理、记忆力衰退等情况，就需要聘请专业护理员上门提供照护服务。',
    },
    {
      question: '护理员、保健员和护士有什么区别？',
      answer:
        '护理员(PCW)提供基本起居照顾；保健员(HW)除了起居照顾外，还可提供伤口护理、管道喂食等医护服务；注册护士(RN/EN)可提供药物注射、抽血、换药等专业医疗服务。选择时应根据长者的实际需求和健康状况。',
    },
    {
      question: '服务时间如何安排？',
      answer:
        '我们提供灵活的服务时间安排，最少2小时起订。服务时间为早上8时至晚上11时，如需深夜或24小时服务，请提前联系客服。建议提前1-3天预约，以确保安排到合适的护理员。',
    },
    {
      question: '如何选择合适的护理员？',
      answer:
        '首先评估长者的健康状况和需求：如果只需要日常照顾和陪伴，选择护理员即可；如果需要伤口护理、管道喂食等，选择保健员；如果需要打针、换药等医疗服务，则需要注册护士。您也可以查看护理员的资质、经验、评价来做选择。',
    },
    {
      question: '价格如何计算？',
      answer:
        '按小时计费，护理员60-80元/小时，保健员100-120元/小时，注册护士150-250元/小时。按天服务有优惠，包月服务更划算。深夜时段（晚11点后）和24小时服务价格会有所调整。',
    },
  ],
  escort: [
    {
      question: '陪诊服务和长者照顾服务有什么区别？',
      answer:
        '陪诊服务主要针对需要就医但无人陪同的长者或病人，服务内容包括护送往返医院、协助挂号取药、与医护人员沟通、监察身体状况等，一般按次计费，3-4小时/次，收费约¥80-150/小时。长者照顾服务则是全面的日常起居照顾，包括饮食、个人卫生、健康监测等，服务时间更长，可按小时、半日、全日或包月计费。',
    },
    {
      question: '什么情况需要陪诊服务？',
      answer:
        '适合以下情况：行动不便的长者需要就医、独居长者无人陪同看病、家属工作繁忙无法请假陪诊、患有慢性病需要定期复诊、术后需要定期覆诊检查、脑退化症患者需要专人陪同。',
    },
    {
      question: '陪诊员需要什么资质？',
      answer:
        '合格的陪诊员需要接受相关护理训练，学习处理伤口、急救知识、扶抱技巧、使用轮椅及助行架等。我们的陪诊员均持有护理员或保健员证书，具备专业医护知识，能够应对各种突发情况。',
    },
    {
      question: '陪诊服务包含哪些内容？',
      answer:
        '服务包括：扶抱行动不便客户上落轮椅、安排外出交通、协助客户检查前更衣换鞋、与医护人员沟通、取药及办理各类手续、监察客户身体状况、仔细聆听医生囑咐、纪录病情并向家人匯报情况。',
    },
  ],
  'medical-staff': [
    {
      question: '医护人员替补方案适合哪些机构？',
      answer:
        '医护人员替补方案主要为公私营医院、护理中心、诊所、安老院舍（老人院）、学校等医疗机构提供短期或长期人手支援。当遇上流感爆发、季节性需求、突发事故、正规医护人员放假、职位空缺等情况时，可以快速配对合适的专业医护人员。',
    },
    {
      question: '可以提供哪些类型的医护人员？',
      answer:
        '我们可以提供：注册/登记护士(RN/EN)，提供专业医疗护理服务；保健员/护理员(HW/PCW)，提供日常护理照顾；治疗师助理(PT/OT/ST助理)，协助康复治疗。所有人员均持证上岗，经验丰富。',
    },
    {
      question: '替补人员可以提供多久的服务？',
      answer:
        '我们提供灵活的服务方案，可以是短期（几天到几周）或长期（几个月到一年）的替补服务。按更计费，一般一更为8-12小时。可以根据机构的实际需求灵活安排。',
    },
    {
      question: '如何保证替补人员的质量？',
      answer:
        '所有医护人员均持有相关专业证书，经过严格筛选和背景审查。我们定期对人员进行培训和考核，确保专业技能和服务质量。如对服务不满意，可随时要求更换人员。',
    },
  ],
};

// 生成头像URL的辅助函数
const generateAvatarUrl = (name: string, index: number): string => {
  const colors = [
    '6366f1', 'ec4899', 'f59e0b', '10b981', '3b82f6',
    '8b5cf6', 'f97316', '06b6d4', '84cc16', 'a855f7'
  ];
  const color = colors[index % colors.length];
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${color}&color=fff&size=200&bold=true`;
};

// 护理人员数据（按服务类型分类）
const caregiversData: Record<ServiceType, Caregiver[]> = {
  'elderly-care': [
    {
      id: '1',
      name: '王美华',
      age: 42,
      avatar: generateAvatarUrl('王美华', 0),
      serviceType: 'elderly-care',
      qualification: 'rn',
      qualificationBadge: 'RN',
      specialty: '老年护理、慢病管理',
      experience: '12年',
      rating: 4.9,
      reviews: 156,
      completedJobs: 200,
      responseTime: '即时可约',
      hourlyRate: 250,
      dailyRate: 2000,
      monthlyRate: 45000,
      certifications: [
        {
          id: 'cert1',
          name: '注册护士证',
          number: 'RN202301234',
          issuer: '香港护士管理局',
          issueDate: '2011-03-15',
          image: '/cert-rn.jpg',
          verified: true,
        },
      ],
      skills: ['老年护理', '慢病管理', '康复训练', '用药管理', '健康监测'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '拥有12年老年护理经验，擅长慢性病管理和康复护理，耐心细致，深受家属好评。',
      detailedIntro: '王美华护士拥有12年三甲医院护理经验，曾任老年科护士长。',
      workHistory: [],
      available: true,
    },
    {
      id: '2',
      name: '李秀英',
      age: 38,
      avatar: generateAvatarUrl('李秀英', 1),
      serviceType: 'elderly-care',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '日常护理、康复协助',
      experience: '8年',
      rating: 4.8,
      reviews: 98,
      completedJobs: 120,
      responseTime: '即时可约',
      hourlyRate: 180,
      dailyRate: 1440,
      monthlyRate: 32000,
      certifications: [],
      skills: ['日常护理', '康复训练', '营养配餐', '健康监测'],
      languages: ['普通话'],
      verified: true,
      featured: true,
      description: '专注于老年人日常护理和康复训练，善于与老人沟通，帮助多位老人恢复生活自理能力。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '3',
      name: '张桂芳',
      age: 48,
      avatar: generateAvatarUrl('张桂芳', 2),
      serviceType: 'elderly-care',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '生活照料、陪伴服务',
      experience: '6年',
      rating: 4.9,
      reviews: 132,
      completedJobs: 150,
      responseTime: '即时可约',
      hourlyRate: 120,
      dailyRate: 960,
      monthlyRate: 21000,
      certifications: [],
      skills: ['生活照料', '情感陪伴', '饮食照顾', '起居协助'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '温柔耐心，擅长与老人建立信任关系，提供贴心的生活照料和情感陪伴。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '4',
      name: '陈丽华',
      age: 45,
      avatar: generateAvatarUrl('陈丽华', 3),
      serviceType: 'elderly-care',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '医疗护理、用药管理',
      experience: '10年',
      rating: 5.0,
      reviews: 89,
      completedJobs: 110,
      responseTime: '需预约',
      hourlyRate: 200,
      dailyRate: 1600,
      monthlyRate: 36000,
      certifications: [],
      skills: ['用药管理', '伤口护理', '健康监测', '慢病管理'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '医疗护理经验丰富，精通用药管理和健康监测，为多位慢性病老人提供专业护理。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '11',
      name: '杨静',
      age: 39,
      avatar: generateAvatarUrl('杨静', 4),
      serviceType: 'elderly-care',
      qualification: 'rn',
      qualificationBadge: 'RN',
      specialty: '糖尿病护理、营养管理',
      experience: '11年',
      rating: 4.9,
      reviews: 145,
      completedJobs: 185,
      responseTime: '即时可约',
      hourlyRate: 230,
      dailyRate: 1840,
      monthlyRate: 42000,
      certifications: [],
      skills: ['糖尿病护理', '营养管理', '血糖监测', '胰岛素注射', '饮食指导'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '擅长糖尿病患者的专业护理，对血糖控制和饮食管理经验丰富，帮助多位患者稳定病情。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '12',
      name: '马丽娟',
      age: 44,
      avatar: generateAvatarUrl('马丽娟', 5),
      serviceType: 'elderly-care',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '失智症护理、行为管理',
      experience: '9年',
      rating: 4.8,
      reviews: 108,
      completedJobs: 135,
      responseTime: '即时可约',
      hourlyRate: 190,
      dailyRate: 1520,
      monthlyRate: 34000,
      certifications: [],
      skills: ['失智症护理', '行为管理', '情绪安抚', '认知训练', '安全防护'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '专注于失智症老人护理，善于处理情绪波动和行为问题，为家属减轻照护压力。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '13',
      name: '许雅琴',
      age: 50,
      avatar: generateAvatarUrl('许雅琴', 6),
      serviceType: 'elderly-care',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '居家照料、卫生护理',
      experience: '7年',
      rating: 4.7,
      reviews: 96,
      completedJobs: 125,
      responseTime: '即时可约',
      hourlyRate: 110,
      dailyRate: 880,
      monthlyRate: 19500,
      certifications: [],
      skills: ['居家照料', '个人卫生', '起居协助', '饮食照顾', '环境清洁'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '亲切和蔼，擅长日常生活照料，注重卫生细节，深受老人和家属信赖。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '14',
      name: '孙梅',
      age: 41,
      avatar: generateAvatarUrl('孙梅', 7),
      serviceType: 'elderly-care',
      qualification: 'rn',
      qualificationBadge: 'EN',
      specialty: '术后康复、伤口护理',
      experience: '13年',
      rating: 5.0,
      reviews: 178,
      completedJobs: 210,
      responseTime: '需预约',
      hourlyRate: 240,
      dailyRate: 1920,
      monthlyRate: 43000,
      certifications: [],
      skills: ['术后康复', '伤口护理', '造口护理', '导尿管护理', '康复训练'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '专业外科护理背景，擅长术后康复和复杂伤口护理，为术后老人提供专业照护。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '15',
      name: '郑秀兰',
      age: 46,
      avatar: generateAvatarUrl('郑秀兰', 8),
      serviceType: 'elderly-care',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '中风康复、肢体训练',
      experience: '10年',
      rating: 4.9,
      reviews: 124,
      completedJobs: 155,
      responseTime: '即时可约',
      hourlyRate: 195,
      dailyRate: 1560,
      monthlyRate: 35000,
      certifications: [],
      skills: ['中风康复', '肢体训练', '吞咽训练', '语言康复', '生活重建'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '专注中风患者康复护理，耐心指导康复训练，帮助多位患者恢复生活能力。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '16',
      name: '何秀芳',
      age: 52,
      avatar: generateAvatarUrl('何秀芳', 9),
      serviceType: 'elderly-care',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '临终关怀、心理陪护',
      experience: '8年',
      rating: 5.0,
      reviews: 87,
      completedJobs: 105,
      responseTime: '即时可约',
      hourlyRate: 115,
      dailyRate: 920,
      monthlyRate: 20000,
      certifications: [],
      skills: ['临终关怀', '心理陪护', '情感支持', '舒适护理', '家属辅导'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '温柔慈祥，擅长临终关怀和心理陪护，为老人提供有尊严的晚年照顾。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
  ],
  escort: [
    {
      id: '5',
      name: '刘芳',
      age: 35,
      avatar: generateAvatarUrl('刘芳', 10),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、医疗翻译',
      experience: '7年',
      rating: 4.9,
      reviews: 112,
      completedJobs: 180,
      responseTime: '即时可约',
      hourlyRate: 120,
      dailyRate: 960,
      monthlyRate: 21000,
      certifications: [],
      skills: ['陪诊护送', '医疗翻译', '急救处理', '病情记录'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '专业陪诊员，擅长与医护人员沟通，能够准确理解医嘱并详细记录病情，为家属提供清晰的汇报。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '6',
      name: '赵敏',
      age: 32,
      avatar: generateAvatarUrl('赵敏', 11),
      serviceType: 'escort',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '陪诊护送、轮椅协助',
      experience: '5年',
      rating: 4.8,
      reviews: 95,
      completedJobs: 150,
      responseTime: '即时可约',
      hourlyRate: 100,
      dailyRate: 800,
      monthlyRate: 18000,
      certifications: [],
      skills: ['轮椅协助', '扶抱技巧', '陪诊护送', '急救处理'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '温柔细心，擅长协助行动不便的长者，提供安全舒适的陪诊护送服务。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '7',
      name: '周慧',
      age: 40,
      avatar: generateAvatarUrl('周慧', 12),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、健康监测',
      experience: '9年',
      rating: 5.0,
      reviews: 87,
      completedJobs: 140,
      responseTime: '需预约',
      hourlyRate: 130,
      dailyRate: 1040,
      monthlyRate: 23000,
      certifications: [],
      skills: ['健康监测', '陪诊护送', '病情记录', '急救处理'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '经验丰富的陪诊员，能够及时发现并处理突发状况，为长者提供全方位的陪诊服务。',
      detailedIntro: '',
      workHistory: [],
      available: false,
    },
    {
      id: '17',
      name: '钱文静',
      age: 36,
      avatar: generateAvatarUrl('钱文静', 13),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、医院导航',
      experience: '6年',
      rating: 4.8,
      reviews: 103,
      completedJobs: 165,
      responseTime: '即时可约',
      hourlyRate: 115,
      dailyRate: 920,
      monthlyRate: 20500,
      certifications: [],
      skills: ['陪诊护送', '医院导航', '挂号取药', '病情记录', '医患沟通'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '熟悉各大医院流程，能高效安排就诊事宜，为患者节省时间，提供贴心陪诊服务。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '18',
      name: '沈玉兰',
      age: 43,
      avatar: generateAvatarUrl('沈玉兰', 14),
      serviceType: 'escort',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '陪诊护送、情感支持',
      experience: '5年',
      rating: 4.9,
      reviews: 89,
      completedJobs: 142,
      responseTime: '即时可约',
      hourlyRate: 95,
      dailyRate: 760,
      monthlyRate: 17000,
      certifications: [],
      skills: ['陪诊护送', '情感支持', '轮椅协助', '生活照顾'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '温柔体贴，善于安抚患者情绪，提供温暖的陪伴和细致的照顾。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '19',
      name: '冯丽',
      age: 38,
      avatar: generateAvatarUrl('冯丽', 15),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、慢病管理',
      experience: '8年',
      rating: 4.7,
      reviews: 126,
      completedJobs: 178,
      responseTime: '即时可约',
      hourlyRate: 125,
      dailyRate: 1000,
      monthlyRate: 22000,
      certifications: [],
      skills: ['慢病管理', '陪诊护送', '用药提醒', '健康记录', '医嘱传达'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '专注慢性病患者陪诊，熟悉常见慢病管理，能准确传达医嘱和健康建议。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '20',
      name: '韩秀珍',
      age: 41,
      avatar: generateAvatarUrl('韩秀珍', 16),
      serviceType: 'escort',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '陪诊护送、交通安排',
      experience: '6年',
      rating: 4.6,
      reviews: 78,
      completedJobs: 128,
      responseTime: '即时可约',
      hourlyRate: 90,
      dailyRate: 720,
      monthlyRate: 16000,
      certifications: [],
      skills: ['交通安排', '陪诊护送', '轮椅使用', '扶抱技巧', '安全护送'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '经验丰富的陪诊员，熟悉公共交通和无障碍设施，确保患者安全舒适就医。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '21',
      name: '姜雪',
      age: 34,
      avatar: generateAvatarUrl('姜雪', 17),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、急救处理',
      experience: '7年',
      rating: 4.9,
      reviews: 115,
      completedJobs: 156,
      responseTime: '即时可约',
      hourlyRate: 135,
      dailyRate: 1080,
      monthlyRate: 24000,
      certifications: [],
      skills: ['急救处理', 'CPR认证', '陪诊护送', '应急响应', '健康监测'],
      languages: ['普通话'],
      verified: true,
      featured: true,
      description: '持有急救证书，应急处理能力强，为行动不便或病情不稳定患者提供专业陪诊。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '22',
      name: '潘美玲',
      age: 39,
      avatar: generateAvatarUrl('潘美玲', 18),
      serviceType: 'escort',
      qualification: 'pcw',
      qualificationBadge: 'PCW',
      specialty: '陪诊护送、老年服务',
      experience: '5年',
      rating: 4.8,
      reviews: 92,
      completedJobs: 138,
      responseTime: '即时可约',
      hourlyRate: 100,
      dailyRate: 800,
      monthlyRate: 18000,
      certifications: [],
      skills: ['老年服务', '陪诊护送', '耐心陪伴', '生活协助', '情绪疏导'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '专注服务老年患者，耐心细致，善于与老人沟通，提供温馨的陪诊体验。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '30',
      name: '郭婷婷',
      age: 30,
      avatar: generateAvatarUrl('郭婷婷', 19),
      serviceType: 'escort',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '陪诊护送、康复指导',
      experience: '4年',
      rating: 4.7,
      reviews: 76,
      completedJobs: 118,
      responseTime: '即时可约',
      hourlyRate: 110,
      dailyRate: 880,
      monthlyRate: 19500,
      certifications: [],
      skills: ['陪诊护送', '康复指导', '健康咨询', '医疗协调', '病历整理'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '年轻有活力，善于与患者沟通，熟悉医院流程，提供高效专业的陪诊服务。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
  ],
  'medical-staff': [
    {
      id: '8',
      name: '林医生',
      age: 50,
      avatar: generateAvatarUrl('林医生', 20),
      serviceType: 'medical-staff',
      qualification: 'rn',
      qualificationBadge: 'RN',
      specialty: '医院替补、专业护理',
      experience: '15年',
      rating: 5.0,
      reviews: 203,
      completedJobs: 300,
      responseTime: '需预约',
      hourlyRate: 280,
      dailyRate: 2240,
      monthlyRate: 50000,
      certifications: [],
      skills: ['专业护理', '医疗操作', 'ICU护理', '急救处理'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '资深注册护士，拥有丰富的医院工作经验，擅长各类专业医疗护理操作。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '9',
      name: '吴护士',
      age: 42,
      avatar: generateAvatarUrl('吴护士', 21),
      serviceType: 'medical-staff',
      qualification: 'rn',
      qualificationBadge: 'EN',
      specialty: '老人院替补、康复护理',
      experience: '10年',
      rating: 4.9,
      reviews: 156,
      completedJobs: 220,
      responseTime: '即时可约',
      hourlyRate: 250,
      dailyRate: 2000,
      monthlyRate: 45000,
      certifications: [],
      skills: ['康复护理', '老年护理', '健康监测', '用药管理'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '专注于老年护理和康复训练，为多家老人院提供专业的替补护理服务。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '10',
      name: '黄治疗师',
      age: 36,
      avatar: generateAvatarUrl('黄治疗师', 22),
      serviceType: 'medical-staff',
      qualification: 'therapist',
      qualificationBadge: 'PT助理',
      specialty: '康复治疗、物理治疗',
      experience: '8年',
      rating: 4.8,
      reviews: 98,
      completedJobs: 160,
      responseTime: '即时可约',
      hourlyRate: 200,
      dailyRate: 1600,
      monthlyRate: 36000,
      certifications: [],
      skills: ['物理治疗', '康复训练', '运动疗法', '功能评估'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '专业的物理治疗助理，擅长协助患者进行康复训练，帮助恢复身体机能。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '23',
      name: '梁护士长',
      age: 48,
      avatar: generateAvatarUrl('梁护士长', 23),
      serviceType: 'medical-staff',
      qualification: 'rn',
      qualificationBadge: 'RN',
      specialty: '老人院管理、护理督导',
      experience: '18年',
      rating: 5.0,
      reviews: 167,
      completedJobs: 265,
      responseTime: '需预约',
      hourlyRate: 300,
      dailyRate: 2400,
      monthlyRate: 55000,
      certifications: [],
      skills: ['护理管理', '团队督导', '质量控制', '应急处理', '老年护理'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '资深护士长，拥有丰富的老人院管理经验，擅长护理团队督导和质量管理。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '24',
      name: '唐注册护士',
      age: 44,
      avatar: generateAvatarUrl('唐注册护士', 24),
      serviceType: 'medical-staff',
      qualification: 'rn',
      qualificationBadge: 'EN',
      specialty: '急症科替补、紧急护理',
      experience: '12年',
      rating: 4.9,
      reviews: 198,
      completedJobs: 285,
      responseTime: '即时可约',
      hourlyRate: 260,
      dailyRate: 2080,
      monthlyRate: 47000,
      certifications: [],
      skills: ['急症护理', '创伤处理', '生命支持', '急救操作', 'IV注射'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '急症科经验丰富，应急能力强，熟练掌握各类急救技能和重症监护。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '25',
      name: '邓保健员',
      age: 40,
      avatar: generateAvatarUrl('邓保健员', 25),
      serviceType: 'medical-staff',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '院舍护理、慢病管理',
      experience: '11年',
      rating: 4.8,
      reviews: 142,
      completedJobs: 205,
      responseTime: '即时可约',
      hourlyRate: 180,
      dailyRate: 1440,
      monthlyRate: 32000,
      certifications: [],
      skills: ['院舍护理', '慢病管理', '用药监测', '健康记录', '伤口护理'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '专注院舍护理工作，熟悉老人院日常护理流程，擅长慢性病患者管理。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '26',
      name: '谢治疗师',
      age: 38,
      avatar: generateAvatarUrl('谢治疗师', 26),
      serviceType: 'medical-staff',
      qualification: 'therapist',
      qualificationBadge: 'OT助理',
      specialty: '职业治疗、日常训练',
      experience: '9年',
      rating: 4.9,
      reviews: 115,
      completedJobs: 175,
      responseTime: '即时可约',
      hourlyRate: 210,
      dailyRate: 1680,
      monthlyRate: 38000,
      certifications: [],
      skills: ['职业治疗', '日常训练', '认知训练', '手部功能', '辅具使用'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: true,
      description: '专业职业治疗助理，帮助患者恢复日常生活能力，提升生活质量。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '27',
      name: '袁护士',
      age: 35,
      avatar: generateAvatarUrl('袁护士', 27),
      serviceType: 'medical-staff',
      qualification: 'rn',
      qualificationBadge: 'RN',
      specialty: '内科护理、透析护理',
      experience: '10年',
      rating: 5.0,
      reviews: 156,
      completedJobs: 230,
      responseTime: '需预约',
      hourlyRate: 270,
      dailyRate: 2160,
      monthlyRate: 49000,
      certifications: [],
      skills: ['内科护理', '腹膜透析', '血液透析', '专科护理', '监测管理'],
      languages: ['普通话', '粤语', '英语'],
      verified: true,
      featured: true,
      description: '内科及透析专科护士，擅长肾病患者护理，具备专业透析护理技能。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '28',
      name: '卢保健员',
      age: 42,
      avatar: generateAvatarUrl('卢保健员', 28),
      serviceType: 'medical-staff',
      qualification: 'hw',
      qualificationBadge: 'HW',
      specialty: '诊所替补、基础护理',
      experience: '8年',
      rating: 4.7,
      reviews: 98,
      completedJobs: 158,
      responseTime: '即时可约',
      hourlyRate: 170,
      dailyRate: 1360,
      monthlyRate: 30000,
      certifications: [],
      skills: ['基础护理', '诊所协助', '消毒处理', '器械准备', '病人护理'],
      languages: ['普通话', '粤语'],
      verified: true,
      featured: false,
      description: '熟悉诊所运作流程，能够协助医生诊疗，提供专业的基础护理服务。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
    {
      id: '29',
      name: '傅治疗师',
      age: 33,
      avatar: generateAvatarUrl('傅治疗师', 29),
      serviceType: 'medical-staff',
      qualification: 'therapist',
      qualificationBadge: 'ST助理',
      specialty: '言语治疗、吞咽训练',
      experience: '6年',
      rating: 4.8,
      reviews: 87,
      completedJobs: 145,
      responseTime: '即时可约',
      hourlyRate: 195,
      dailyRate: 1560,
      monthlyRate: 35000,
      certifications: [],
      skills: ['言语治疗', '吞咽训练', '发音矫正', '沟通辅助', '康复评估'],
      languages: ['普通话'],
      verified: true,
      featured: false,
      description: '专业言语治疗助理，擅长帮助中风或失语患者恢复语言和吞咽功能。',
      detailedIntro: '',
      workHistory: [],
      available: true,
    },
  ],
};

// 服务导出函数
export const getCaregiversByServiceType = (serviceType: ServiceType): Caregiver[] => {
  return caregiversData[serviceType] || [];
};

export const filterCaregiversByQualification = (caregivers: Caregiver[], qualification: string): Caregiver[] => {
  if (qualification === 'all') return caregivers;
  return caregivers.filter((c) => c.qualification === qualification);
};

export const getFeaturedCaregivers = (caregivers: Caregiver[]): Caregiver[] => {
  return caregivers.filter((c) => c.featured);
};

export const getNonFeaturedCaregivers = (caregivers: Caregiver[]): Caregiver[] => {
  return caregivers.filter((c) => !c.featured);
};

// 根据ID获取护理员
export const getCaregiverById = (caregiverId: string): Caregiver | null => {
  const allCaregivers = [
    ...getCaregiversByServiceType('elderly-care'),
    ...getCaregiversByServiceType('escort'),
    ...getCaregiversByServiceType('medical-staff'),
  ];
  return allCaregivers.find(c => c.id === caregiverId) || null;
};

// 根据ID获取服务套餐
export const getPackageById = (packageId: string): ServicePackage | null => {
  return servicePackages.find(p => p.id === packageId) || null;
};
