/**
 * 保险产品数据服务
 * Insurance Product Data Service
 */

import { InsuranceProduct, InsuranceCompany, InsuranceCategory } from '@/types/insurance';

// Mock 数据 - 保险公司（真实南方/珠三角保险公司）
const mockCompanies: InsuranceCompany[] = [
  {
    id: 'company_001',
    name: '平安人寿',
    logo: 'https://www.chinalife.com.cn/favicon.ico',
    foundedYear: 1988,
    registeredCapital: '338亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AAA',
    solvencyRatio: '245%',
    claimTimeAvg: '0.8天',
    claimSuccessRate: '99.1%',
    customerServiceHotline: '95511',
    productCount: 156,
    description: '中国平安人寿保险股份有限公司，总部位于深圳，中国三大综合金融集团之一',
    website: 'https://life.pingan.com',
  },
  {
    id: 'company_002',
    name: '招商信诺',
    logo: 'https://www.cignacmb.com/favicon.ico',
    foundedYear: 2003,
    registeredCapital: '23亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AA',
    solvencyRatio: '298%',
    claimTimeAvg: '1.1天',
    claimSuccessRate: '98.8%',
    customerServiceHotline: '95362',
    productCount: 78,
    description: '招商信诺人寿保险有限公司，总部位于深圳，中外合资寿险公司',
    website: 'https://www.cignacmb.com',
  },
  {
    id: 'company_003',
    name: '友邦保险',
    logo: 'https://www.aia.com.cn/favicon.ico',
    foundedYear: 1992,
    registeredCapital: '37亿美元',
    cbircRating: 'A',
    thirdPartyRating: 'AA+',
    solvencyRatio: '425%',
    claimTimeAvg: '0.6天',
    claimSuccessRate: '99.3%',
    customerServiceHotline: '400-820-3588',
    productCount: 92,
    description: '友邦保险（AIA），总部位于香港，在广州、深圳设有分公司，百年外资险企',
    website: 'https://www.aia.com.cn',
  },
  {
    id: 'company_004',
    name: '太平人寿',
    logo: 'https://www.tplife.com/favicon.ico',
    foundedYear: 1929,
    registeredCapital: '100.3亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AA',
    solvencyRatio: '267%',
    claimTimeAvg: '1.0天',
    claimSuccessRate: '98.6%',
    customerServiceHotline: '95589',
    productCount: 118,
    description: '中国太平人寿保险有限公司，总部位于香港，在广州、深圳、珠海设有分公司',
    website: 'https://www.tplife.com',
  },
  {
    id: 'company_005',
    name: '众安保险',
    logo: 'https://www.zhongan.com/favicon.ico',
    foundedYear: 2013,
    registeredCapital: '15亿元',
    cbircRating: 'B+',
    thirdPartyRating: 'A',
    solvencyRatio: '385%',
    claimTimeAvg: '0.5天',
    claimSuccessRate: '97.8%',
    customerServiceHotline: '1010-9955',
    productCount: 134,
    description: '众安在线财产保险股份有限公司，中国首家互联网保险公司，服务粤港澳大湾区',
    website: 'https://www.zhongan.com',
  },
  {
    id: 'company_006',
    name: '泰康人寿',
    logo: 'https://www.taikang.com/favicon.ico',
    foundedYear: 1996,
    registeredCapital: '114亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AA+',
    solvencyRatio: '278%',
    claimTimeAvg: '0.9天',
    claimSuccessRate: '98.9%',
    customerServiceHotline: '95522',
    productCount: 145,
    description: '泰康保险集团，在广州、深圳设有大型分公司，拥有泰康之家·粤园养老社区',
    website: 'https://www.taikang.com',
  },
  {
    id: 'company_007',
    name: '新华保险',
    logo: 'https://www.newchinalife.com/favicon.ico',
    foundedYear: 1996,
    registeredCapital: '31.2亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AA',
    solvencyRatio: '234%',
    claimTimeAvg: '1.3天',
    claimSuccessRate: '98.2%',
    customerServiceHotline: '95567',
    productCount: 103,
    description: '新华人寿保险股份有限公司，在珠三角地区拥有完善的服务网络',
    website: 'https://www.newchinalife.com',
  },
  {
    id: 'company_008',
    name: '中国人寿',
    logo: 'https://www.chinalife.com.cn/favicon.ico',
    foundedYear: 1949,
    registeredCapital: '282.65亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AAA',
    solvencyRatio: '256%',
    claimTimeAvg: '1.2天',
    claimSuccessRate: '98.5%',
    customerServiceHotline: '95519',
    productCount: 198,
    description: '中国人寿保险股份有限公司，中国最大的寿险公司，在广东省设有省级分公司',
    website: 'https://www.chinalife.com.cn',
  },
  {
    id: 'company_009',
    name: '阳光人寿',
    logo: 'https://life.sinosig.com/favicon.ico',
    foundedYear: 2007,
    registeredCapital: '67.6亿元',
    cbircRating: 'A',
    thirdPartyRating: 'AA',
    solvencyRatio: '312%',
    claimTimeAvg: '0.7天',
    claimSuccessRate: '98.4%',
    customerServiceHotline: '95510',
    productCount: 87,
    description: '阳光人寿保险股份有限公司，在深圳、广州等地设有分公司，主打互联网保险',
    website: 'https://life.sinosig.com',
  },
  {
    id: 'company_010',
    name: '富德生命人寿',
    logo: 'https://www.sino-life.com/favicon.ico',
    foundedYear: 2002,
    registeredCapital: '117.52亿元',
    cbircRating: 'B+',
    thirdPartyRating: 'AA',
    solvencyRatio: '186%',
    claimTimeAvg: '1.4天',
    claimSuccessRate: '97.9%',
    customerServiceHotline: '95535',
    productCount: 96,
    description: '富德生命人寿保险股份有限公司，总部位于深圳，深耕华南市场',
    website: 'https://www.sino-life.com',
  },
];

// Mock 数据 - 保险产品（30+真实产品）
const mockProducts: InsuranceProduct[] = [
  // ========== 医疗险 (8个产品) ==========
  {
    id: 'product_001',
    name: '平安e生保·长期医疗险',
    companyId: 'company_001',
    companyName: '平安人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'medical',
    subCategory: '百万医疗',
    description: '600万医疗保障，保证续保20年，覆盖特殊门诊和住院，包含质子重离子治疗，深圳投保可享绿色就医通道',
    highlights: [
      '保证续保20年',
      '600万医疗保额',
      '质子重离子100%报销',
      '深圳地区绿通服务',
      '院外特药全覆盖',
    ],
    coverageDetails: [
      {
        name: '一般住院医疗',
        type: 'primary',
        description: '住院期间的医疗费用',
        coverageAmount: '400万',
        claimRatio: '100%（扣除1万免赔额）',
        waitingPeriod: '30天',
      },
      {
        name: '重疾住院医疗',
        type: 'primary',
        description: '确诊重大疾病后的住院医疗',
        coverageAmount: '600万',
        claimRatio: '100%（0免赔）',
        waitingPeriod: '30天',
      },
      {
        name: '质子重离子治疗',
        type: 'additional',
        description: '癌症质子重离子治疗费用',
        coverageAmount: '600万',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 70 },
    healthRequirements: '需如实告知健康状况，部分慢性病可投保',
    occupationLimits: ['1-4类职业'],
    coverageAmountRange: { min: 400, max: 600 },
    premiumStartFrom: 298,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保20年）'],
    policyDocumentUrl: 'https://life.pingan.com/policy.pdf',
    purchaseUrl: 'https://life.pingan.com/product/medical',
    tags: ['guaranteed_renewal', 'high_value', 'big_company'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 18920,
    rating: 4.8,
    reviewCount: 12580,
    launchDate: '2024-01-15',
    updatedAt: '2024-11-12',
  },
  {
    id: 'product_002',
    name: '众安尊享e生2024',
    companyId: 'company_005',
    companyName: '众安保险',
    companyLogo: 'https://www.zhongan.com/favicon.ico',
    category: 'medical',
    subCategory: '百万医疗',
    description: '互联网百万医疗险领军产品，400万保额，可保既往症，适合广东地区三高人群',
    highlights: [
      '可保既往症',
      '三高人群可投',
      '外购药100%报销',
      '深圳三甲医院绿通',
      '在线理赔秒到账',
    ],
    coverageDetails: [
      {
        name: '一般医疗',
        type: 'primary',
        description: '住院医疗费用',
        coverageAmount: '400万',
        claimRatio: '100%（1万免赔）',
        waitingPeriod: '30天',
      },
      {
        name: '既往症医疗',
        type: 'additional',
        description: '投保前已有疾病的治疗费用',
        coverageAmount: '100万',
        claimRatio: '70%',
      },
    ],
    ageRange: { min: 0, max: 65 },
    healthRequirements: '健康告知宽松，三高糖尿病可投',
    coverageAmountRange: { min: 400, max: 400 },
    premiumStartFrom: 376,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://www.zhongan.com/zunjiangeshen',
    tags: ['no_medical_exam', 'fast_claim', 'chronic_disease'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 15670,
    rating: 4.7,
    reviewCount: 9850,
    launchDate: '2024-02-01',
    updatedAt: '2024-11-10',
  },
  {
    id: 'product_003',
    name: '招商信诺·臻爱无限2024',
    companyId: 'company_002',
    companyName: '招商信诺',
    companyLogo: 'https://www.cignacmb.com/favicon.ico',
    category: 'medical',
    subCategory: '百万医疗',
    description: '深圳本土保险公司出品，800万医疗保障，含重疾津贴，深圳地区专享服务',
    highlights: [
      '800万超高保额',
      '重疾津贴1万/年',
      '深圳就医VIP通道',
      '家庭单优惠15%',
      '保证续保至105岁',
    ],
    coverageDetails: [
      {
        name: '住院医疗',
        type: 'primary',
        description: '住院治疗费用',
        coverageAmount: '800万',
        claimRatio: '100%（1万免赔）',
        waitingPeriod: '30天',
      },
      {
        name: '重疾津贴',
        type: 'additional',
        description: '确诊重疾后每年给付',
        coverageAmount: '1万元/年',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '标准体投保',
    coverageAmountRange: { min: 800, max: 800 },
    premiumStartFrom: 468,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保至105岁）'],
    purchaseUrl: 'https://www.cignacmb.com/medical',
    tags: ['guaranteed_renewal', 'big_company', 'high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 8920,
    rating: 4.9,
    reviewCount: 5670,
    launchDate: '2024-03-15',
    updatedAt: '2024-11-08',
  },
  {
    id: 'product_004',
    name: '友邦传世无忧·医疗保障计划',
    companyId: 'company_003',
    companyName: '友邦保险',
    companyLogo: 'https://www.aia.com.cn/favicon.ico',
    category: 'medical',
    subCategory: '高端医疗',
    description: '外资高端医疗险，覆盖广州、深圳、香港私立医院，无免赔额，含海外就医',
    highlights: [
      '私立医院直付',
      '港澳地区就医',
      '无免赔额',
      '含海外紧急救援',
      '家庭医生服务',
    ],
    coverageDetails: [
      {
        name: '住院医疗',
        type: 'primary',
        description: '公私立医院住院费用',
        coverageAmount: '2000万',
        claimRatio: '100%（0免赔）',
      },
      {
        name: '海外就医',
        type: 'additional',
        description: '境外医疗费用',
        coverageAmount: '500万',
        claimRatio: '80%',
      },
    ],
    ageRange: { min: 0, max: 65 },
    healthRequirements: '需体检',
    coverageAmountRange: { min: 2000, max: 2000 },
    premiumStartFrom: 12800,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://www.aia.com.cn/medical-premium',
    tags: ['big_company', 'specialized', 'no_medical_exam'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 1250,
    rating: 4.9,
    reviewCount: 890,
    launchDate: '2023-10-01',
    updatedAt: '2024-10-20',
  },
  {
    id: 'product_005',
    name: '太平医无忧·特需版',
    companyId: 'company_004',
    companyName: '太平人寿',
    companyLogo: 'https://www.tplife.com/favicon.ico',
    category: 'medical',
    subCategory: '中端医疗',
    description: '覆盖特需部、国际部，广州、深圳三甲医院特需病房直付',
    highlights: [
      '特需部0免赔',
      '广深医院绿通',
      '儿童齿科保障',
      '重疾二次诊疗',
      '保证续保6年',
    ],
    coverageDetails: [
      {
        name: '特需部医疗',
        type: 'primary',
        description: '三甲医院特需部费用',
        coverageAmount: '300万',
        claimRatio: '100%（0免赔）',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 300, max: 300 },
    premiumStartFrom: 3680,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保6年）'],
    purchaseUrl: 'https://www.tplife.com/medical-premium',
    tags: ['guaranteed_renewal', 'big_company'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 2340,
    rating: 4.8,
    reviewCount: 1560,
    launchDate: '2024-04-10',
    updatedAt: '2024-11-05',
  },
  {
    id: 'product_006',
    name: '众安·惠享e生',
    companyId: 'company_005',
    companyName: '众安保险',
    companyLogo: 'https://www.zhongan.com/favicon.ico',
    category: 'medical',
    subCategory: '惠民医疗',
    description: '政府指导惠民医疗险，深圳市医保参保人专享，不限年龄，不限既往症',
    highlights: [
      '政府指导产品',
      '深圳医保专享',
      '不限年龄',
      '既往症可保',
      '价格惠民',
    ],
    coverageDetails: [
      {
        name: '住院医疗',
        type: 'primary',
        description: '社保内外住院费用',
        coverageAmount: '200万',
        claimRatio: '80%（2万免赔）',
      },
      {
        name: '特药保障',
        type: 'additional',
        description: '恶性肿瘤特效药',
        coverageAmount: '100万',
        claimRatio: '80%',
      },
    ],
    ageRange: { min: 0, max: 100 },
    healthRequirements: '无健康告知',
    coverageAmountRange: { min: 200, max: 200 },
    premiumStartFrom: 168,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://www.zhongan.com/huimin',
    tags: ['no_medical_exam', 'high_value', 'chronic_disease'],
    ageGroups: ['50-60', '60-70', '70+', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 25600,
    rating: 4.6,
    reviewCount: 18900,
    launchDate: '2024-01-01',
    updatedAt: '2024-11-12',
  },
  {
    id: 'product_007',
    name: '泰康健康尊享D款',
    companyId: 'company_006',
    companyName: '泰康人寿',
    companyLogo: 'https://www.taikang.com/favicon.ico',
    category: 'medical',
    subCategory: '百万医疗',
    description: '附带泰康之家养老社区入住权，广州粤园、深圳鹏园优先入住',
    highlights: [
      '养老社区入住权',
      '600万医疗保额',
      '泰康自有医院直付',
      '保证续保15年',
      '家庭单享折扣',
    ],
    coverageDetails: [
      {
        name: '一般医疗',
        type: 'primary',
        description: '住院医疗费用',
        coverageAmount: '600万',
        claimRatio: '100%（1万免赔）',
      },
    ],
    ageRange: { min: 0, max: 65 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 600, max: 600 },
    premiumStartFrom: 398,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保15年）'],
    purchaseUrl: 'https://www.taikang.com/medical',
    tags: ['guaranteed_renewal', 'big_company', 'high_value'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 7890,
    rating: 4.8,
    reviewCount: 4560,
    launchDate: '2024-05-20',
    updatedAt: '2024-11-01',
  },
  {
    id: 'product_008',
    name: '新华康健华贵B款',
    companyId: 'company_007',
    companyName: '新华保险',
    companyLogo: 'https://www.newchinalife.com/favicon.ico',
    category: 'medical',
    subCategory: '百万医疗',
    description: '性价比之选，珠三角地区专供版，含住院垫付服务',
    highlights: [
      '超高性价比',
      '住院费用垫付',
      '珠三角专供',
      '保证续保10年',
      '癌症津贴',
    ],
    coverageDetails: [
      {
        name: '一般医疗',
        type: 'primary',
        description: '住院医疗费用',
        coverageAmount: '300万',
        claimRatio: '100%（1万免赔）',
      },
      {
        name: '癌症津贴',
        type: 'additional',
        description: '确诊恶性肿瘤给付',
        coverageAmount: '1万元',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 300, max: 300 },
    premiumStartFrom: 268,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保10年）'],
    purchaseUrl: 'https://www.newchinalife.com/medical',
    tags: ['high_value', 'guaranteed_renewal'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 6780,
    rating: 4.7,
    reviewCount: 3890,
    launchDate: '2024-06-01',
    updatedAt: '2024-10-28',
  },

  // ========== 重疾险/防癌险 (8个产品) ==========
  {
    id: 'product_009',
    name: '平安盛世福尊享版',
    companyId: 'company_001',
    companyName: '平安人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'critical_illness',
    subCategory: '重疾险',
    description: '深圳本土重疾险标杆产品，120种重疾+60种轻中症，含身故责任',
    highlights: [
      '120种重疾',
      '中症赔付60%',
      '轻症赔付30%',
      '深圳地区加10%',
      '保至70/80岁可选',
    ],
    coverageDetails: [
      {
        name: '重大疾病',
        type: 'primary',
        description: '120种重疾赔付',
        coverageAmount: '50万',
        claimRatio: '100%基本保额',
        waitingPeriod: '90天',
      },
      {
        name: '中症疾病',
        type: 'additional',
        description: '35种中症赔付',
        coverageAmount: '30万',
        claimRatio: '60%基本保额',
      },
      {
        name: '轻症疾病',
        type: 'additional',
        description: '60种轻症赔付',
        coverageAmount: '15万',
        claimRatio: '30%基本保额',
      },
    ],
    ageRange: { min: 0, max: 55 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 200000, max: 1000000 },
    premiumStartFrom: 5680,
    paymentPeriods: ['10年交', '15年交', '20年交', '30年交'],
    coveragePeriods: ['至70岁', '至80岁', '终身'],
    purchaseUrl: 'https://life.pingan.com/critical-illness',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 4560,
    rating: 4.9,
    reviewCount: 2890,
    launchDate: '2023-11-01',
    updatedAt: '2024-11-10',
  },
  {
    id: 'product_010',
    name: '众安康享一生',
    companyId: 'company_005',
    companyName: '众安保险',
    companyLogo: 'https://www.zhongan.com/favicon.ico',
    category: 'critical_illness',
    subCategory: '防癌险',
    description: '专为中老年设计的防癌医疗险，70岁可投，三高人群可投保，保证续保终身',
    highlights: [
      '70岁可投保',
      '三高人群可保',
      '保证续保终身',
      '400万癌症医疗',
      '院外靶向药报销',
    ],
    coverageDetails: [
      {
        name: '恶性肿瘤医疗',
        type: 'primary',
        description: '确诊癌症后的医疗费用',
        coverageAmount: '400万',
        claimRatio: '100%（0免赔）',
        waitingPeriod: '90天',
      },
      {
        name: '原位癌医疗',
        type: 'additional',
        description: '原位癌治疗费用',
        coverageAmount: '10万',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 45, max: 70 },
    healthRequirements: '三高、糖尿病等慢性病可投保，无需体检',
    coverageAmountRange: { min: 400, max: 400 },
    premiumStartFrom: 488,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年（保证续保终身）'],
    purchaseUrl: 'https://www.zhongan.com/cancer-medical',
    tags: ['no_medical_exam', 'guaranteed_renewal', 'chronic_disease', 'specialized'],
    ageGroups: ['50-60', '60-70', '70+'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 11250,
    rating: 4.7,
    reviewCount: 7890,
    launchDate: '2024-03-20',
    updatedAt: '2024-11-10',
  },
  {
    id: 'product_011',
    name: '友邦全佑惠选2.0',
    companyId: 'company_003',
    companyName: '友邦保险',
    companyLogo: 'https://www.aia.com.cn/favicon.ico',
    category: 'critical_illness',
    subCategory: '重疾险',
    description: '外资险企王牌重疾，港澳地区认可，含疾病终末期保障',
    highlights: [
      '外资公司产品',
      '港澳地区认可',
      '疾病终末期保障',
      '保额分组赔付',
      '重疾不分组',
    ],
    coverageDetails: [
      {
        name: '重大疾病',
        type: 'primary',
        description: '110种重疾不分组',
        coverageAmount: '50万',
        claimRatio: '100%',
        waitingPeriod: '90天',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 300000, max: 1500000 },
    premiumStartFrom: 6890,
    paymentPeriods: ['15年交', '20年交', '30年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.aia.com.cn/critical',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 2340,
    rating: 4.9,
    reviewCount: 1560,
    launchDate: '2023-09-15',
    updatedAt: '2024-10-25',
  },
  {
    id: 'product_012',
    name: '太平福禄康瑞2024',
    companyId: 'company_004',
    companyName: '太平人寿',
    companyLogo: 'https://www.tplife.com/favicon.ico',
    category: 'critical_illness',
    subCategory: '重疾险',
    description: '港资险企产品，广州、深圳、珠海专供，含癌症多次赔付',
    highlights: [
      '癌症3次赔付',
      '心脑血管2次赔',
      '珠三角专供',
      '保费豁免',
      '身故返保费',
    ],
    coverageDetails: [
      {
        name: '重大疾病',
        type: 'primary',
        description: '108种重疾',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
      {
        name: '癌症多次赔付',
        type: 'additional',
        description: '间隔3年可再赔',
        coverageAmount: '50万×3次',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 55 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 200000, max: 800000 },
    premiumStartFrom: 6120,
    paymentPeriods: ['15年交', '20年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.tplife.com/critical',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 3120,
    rating: 4.8,
    reviewCount: 1890,
    launchDate: '2024-02-10',
    updatedAt: '2024-11-02',
  },
  {
    id: 'product_013',
    name: '泰康惠享2024',
    companyId: 'company_006',
    companyName: '泰康人寿',
    companyLogo: 'https://www.taikang.com/favicon.ico',
    category: 'critical_illness',
    subCategory: '防癌险',
    description: '定期防癌险，保至80岁，适合预算有限的中老年人',
    highlights: [
      '专保恶性肿瘤',
      '保费低廉',
      '健康告知宽松',
      '保至80岁',
      '可续保终身',
    ],
    coverageDetails: [
      {
        name: '恶性肿瘤',
        type: 'primary',
        description: '确诊即赔',
        coverageAmount: '30万',
        claimRatio: '100%',
        waitingPeriod: '90天',
      },
    ],
    ageRange: { min: 45, max: 70 },
    healthRequirements: '健康告知宽松',
    coverageAmountRange: { min: 100000, max: 500000 },
    premiumStartFrom: 1280,
    paymentPeriods: ['10年交', '15年交', '20年交'],
    coveragePeriods: ['至80岁', '终身'],
    purchaseUrl: 'https://www.taikang.com/cancer',
    tags: ['high_value', 'no_medical_exam'],
    ageGroups: ['50-60', '60-70', '70+'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 5670,
    rating: 4.6,
    reviewCount: 3450,
    launchDate: '2024-04-01',
    updatedAt: '2024-10-30',
  },
  {
    id: 'product_014',
    name: '新华i守护重疾险',
    companyId: 'company_007',
    companyName: '新华保险',
    companyLogo: 'https://www.newchinalife.com/favicon.ico',
    category: 'critical_illness',
    subCategory: '重疾险',
    description: '高性价比重疾险，含疾病关爱金，珠三角地区专供',
    highlights: [
      '性价比之王',
      '首次重疾额外赔',
      '疾病关爱金',
      '保费低至5折',
      '可选身故责任',
    ],
    coverageDetails: [
      {
        name: '重大疾病',
        type: 'primary',
        description: '100种重疾',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 55 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 200000, max: 600000 },
    premiumStartFrom: 4560,
    paymentPeriods: ['15年交', '20年交', '30年交'],
    coveragePeriods: ['至70岁', '终身'],
    purchaseUrl: 'https://www.newchinalife.com/critical',
    tags: ['high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 4230,
    rating: 4.7,
    reviewCount: 2560,
    launchDate: '2024-05-10',
    updatedAt: '2024-11-01',
  },
  {
    id: 'product_015',
    name: '中国人寿国寿福庆典版',
    companyId: 'company_008',
    companyName: '中国人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'critical_illness',
    subCategory: '重疾险',
    description: '国寿王牌重疾险，广东省分公司特供，含特定疾病额外赔',
    highlights: [
      '大公司产品',
      '120种重疾',
      '特定疾病双倍赔',
      '保费豁免全面',
      '可附加两全',
    ],
    coverageDetails: [
      {
        name: '重大疾病',
        type: 'primary',
        description: '120种重疾',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
      {
        name: '特定重疾',
        type: 'additional',
        description: '10种特定重疾',
        coverageAmount: '50万',
        claimRatio: '额外100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 200000, max: 1000000 },
    premiumStartFrom: 6780,
    paymentPeriods: ['10年交', '15年交', '20年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.chinalife.com.cn/critical',
    tags: ['big_company'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 8900,
    rating: 4.8,
    reviewCount: 5670,
    launchDate: '2023-12-01',
    updatedAt: '2024-11-05',
  },
  {
    id: 'product_016',
    name: '阳光爱健康2024',
    companyId: 'company_009',
    companyName: '阳光人寿',
    companyLogo: 'https://life.sinosig.com/favicon.ico',
    category: 'critical_illness',
    subCategory: '防癌险',
    description: '互联网防癌险，保费低廉，适合三高糖尿病人群',
    highlights: [
      '三高可投',
      '糖尿病可投',
      '原位癌也赔',
      '保费超低',
      '核保宽松',
    ],
    coverageDetails: [
      {
        name: '恶性肿瘤',
        type: 'primary',
        description: '确诊即赔',
        coverageAmount: '20万',
        claimRatio: '100%',
        waitingPeriod: '180天',
      },
      {
        name: '原位癌',
        type: 'additional',
        description: '轻度恶性肿瘤',
        coverageAmount: '4万',
        claimRatio: '20%',
      },
    ],
    ageRange: { min: 45, max: 75 },
    healthRequirements: '无需体检',
    coverageAmountRange: { min: 100000, max: 300000 },
    premiumStartFrom: 680,
    paymentPeriods: ['10年交', '15年交'],
    coveragePeriods: ['至80岁'],
    purchaseUrl: 'https://life.sinosig.com/cancer',
    tags: ['no_medical_exam', 'high_value', 'chronic_disease'],
    ageGroups: ['50-60', '60-70', '70+'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 6890,
    rating: 4.5,
    reviewCount: 4120,
    launchDate: '2024-06-15',
    updatedAt: '2024-10-28',
  },

  // ========== 年金险 (6个产品) ==========
  {
    id: 'product_017',
    name: '平安盛世金越',
    companyId: 'company_001',
    companyName: '平安人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'annuity',
    subCategory: '养老年金',
    description: '深圳本土养老年金标杆，终身领取，活多久领多久，含养老社区入住权',
    highlights: [
      '终身领取',
      '保证领取20年',
      '深圳养老社区',
      '收益写入合同',
      '支持减保取现',
    ],
    coverageDetails: [
      {
        name: '养老年金',
        type: 'primary',
        description: '60岁起按年领取',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
      {
        name: '保证领取',
        type: 'primary',
        description: '保证领取20年',
        coverageAmount: '剩余年金',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '无需健康告知',
    coverageAmountRange: { min: 50000, max: 10000000 },
    premiumStartFrom: 50000,
    paymentPeriods: ['3年交', '5年交', '10年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://life.pingan.com/annuity',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 1890,
    rating: 4.9,
    reviewCount: 1230,
    launchDate: '2023-10-01',
    updatedAt: '2024-11-01',
  },
  {
    id: 'product_018',
    name: '招商信诺自在人生A款',
    companyId: 'company_002',
    companyName: '招商信诺',
    companyLogo: 'https://www.cignacmb.com/favicon.ico',
    category: 'annuity',
    subCategory: '养老年金',
    description: '深圳本地出品，月领年金，活多久领多久，可对接养老社区',
    highlights: [
      '按月领取',
      '领取灵活',
      '收益稳定',
      '保证领取25年',
      '深圳社区优先',
    ],
    coverageDetails: [
      {
        name: '养老年金',
        type: 'primary',
        description: '按月或按年领取',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '无',
    coverageAmountRange: { min: 50000, max: 5000000 },
    premiumStartFrom: 50000,
    paymentPeriods: ['3年交', '5年交', '10年交', '20年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.cignacmb.com/annuity',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 1560,
    rating: 4.8,
    reviewCount: 980,
    launchDate: '2024-01-20',
    updatedAt: '2024-10-25',
  },
  {
    id: 'product_019',
    name: '泰康赢悦人生',
    companyId: 'company_006',
    companyName: '泰康人寿',
    companyLogo: 'https://www.taikang.com/favicon.ico',
    category: 'annuity',
    subCategory: '养老年金',
    description: '附带泰康之家入住权，广州粤园、深圳鹏园养老社区优先入住',
    highlights: [
      '养老社区入住权',
      '医养结合',
      '终身领取',
      '广深专享服务',
      '保证领取',
    ],
    coverageDetails: [
      {
        name: '养老年金',
        type: 'primary',
        description: '约定年龄开始领取',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '无',
    coverageAmountRange: { min: 200000, max: 10000000 },
    premiumStartFrom: 200000,
    paymentPeriods: ['3年交', '5年交', '10年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.taikang.com/annuity',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 2340,
    rating: 4.9,
    reviewCount: 1560,
    launchDate: '2023-11-10',
    updatedAt: '2024-11-02',
  },
  {
    id: 'product_020',
    name: '中国人寿鑫耀东方',
    companyId: 'company_008',
    companyName: '中国人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'annuity',
    subCategory: '养老年金',
    description: '国寿王牌年金，快速返还，收益稳定，广东省专供版',
    highlights: [
      '快速返还',
      '5年回本',
      '收益确定',
      '保证领取',
      '大公司保障',
    ],
    coverageDetails: [
      {
        name: '生存金',
        type: 'primary',
        description: '每年领取生存金',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 65 },
    healthRequirements: '无',
    coverageAmountRange: { min: 50000, max: 5000000 },
    premiumStartFrom: 50000,
    paymentPeriods: ['3年交', '5年交'],
    coveragePeriods: ['至85岁'],
    purchaseUrl: 'https://www.chinalife.com.cn/annuity',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 3120,
    rating: 4.8,
    reviewCount: 2890,
    launchDate: '2023-12-15',
    updatedAt: '2024-11-05',
  },
  {
    id: 'product_021',
    name: '太平悦享金生',
    companyId: 'company_004',
    companyName: '太平人寿',
    companyLogo: 'https://www.tplife.com/favicon.ico',
    category: 'annuity',
    subCategory: '年金险',
    description: '港资品质，珠三角专供，教育金养老金两用',
    highlights: [
      '教育养老两用',
      '领取灵活',
      '收益稳定',
      '万能账户',
      '珠三角专供',
    ],
    coverageDetails: [
      {
        name: '年金给付',
        type: 'primary',
        description: '按合同约定给付',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 60 },
    healthRequirements: '无',
    coverageAmountRange: { min: 50000, max: 3000000 },
    premiumStartFrom: 50000,
    paymentPeriods: ['3年交', '5年交', '10年交'],
    coveragePeriods: ['至88岁'],
    purchaseUrl: 'https://www.tplife.com/annuity',
    tags: ['big_company'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 1780,
    rating: 4.7,
    reviewCount: 1120,
    launchDate: '2024-03-01',
    updatedAt: '2024-10-20',
  },
  {
    id: 'product_022',
    name: '新华尊享年年',
    companyId: 'company_007',
    companyName: '新华保险',
    companyLogo: 'https://www.newchinalife.com/favicon.ico',
    category: 'annuity',
    subCategory: '年金险',
    description: '高现价年金，支持减保，灵活取现，珠三角性价比之选',
    highlights: [
      '高现金价值',
      '支持减保',
      '灵活取现',
      '收益稳定',
      '超高性价比',
    ],
    coverageDetails: [
      {
        name: '生存年金',
        type: 'primary',
        description: '每年领取',
        coverageAmount: '根据投保金额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 65 },
    healthRequirements: '无',
    coverageAmountRange: { min: 50000, max: 2000000 },
    premiumStartFrom: 50000,
    paymentPeriods: ['3年交', '5年交', '10年交'],
    coveragePeriods: ['至终身'],
    purchaseUrl: 'https://www.newchinalife.com/annuity',
    tags: ['high_value'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 1450,
    rating: 4.6,
    reviewCount: 890,
    launchDate: '2024-04-15',
    updatedAt: '2024-10-30',
  },

  // ========== 意外险 (4个产品) ==========
  {
    id: 'product_023',
    name: '众安综合意外险·全面保',
    companyId: 'company_005',
    companyName: '众安保险',
    companyLogo: 'https://www.zhongan.com/favicon.ico',
    category: 'accident',
    subCategory: '综合意外',
    description: '50万意外保障，含猝死责任，意外医疗0免赔，支持社保外用药',
    highlights: [
      '50万意外身故',
      '含猝死责任',
      '5万意外医疗',
      '0免赔额',
      '社保外用药',
    ],
    coverageDetails: [
      {
        name: '意外身故/伤残',
        type: 'primary',
        description: '意外导致的身故或伤残',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
      {
        name: '意外医疗',
        type: 'primary',
        description: '意外导致的医疗费用',
        coverageAmount: '5万',
        claimRatio: '100%（0免赔）',
      },
      {
        name: '猝死责任',
        type: 'additional',
        description: '猝死保障',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 18, max: 75 },
    healthRequirements: '无健康告知',
    coverageAmountRange: { min: 500000, max: 1000000 },
    premiumStartFrom: 298,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://www.zhongan.com/accident',
    tags: ['no_medical_exam', 'high_value', 'fast_claim'],
    ageGroups: ['50-60', '60-70', '70+', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 16780,
    rating: 4.6,
    reviewCount: 10230,
    launchDate: '2024-05-01',
    updatedAt: '2024-11-05',
  },
  {
    id: 'product_024',
    name: '平安百万护身福',
    companyId: 'company_001',
    companyName: '平安人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'accident',
    subCategory: '综合意外',
    description: '100万意外保障，深圳地区专享，公共交通双倍赔',
    highlights: [
      '100万意外保障',
      '公交双倍赔',
      '深圳专享',
      '含住院津贴',
      '紧急救援',
    ],
    coverageDetails: [
      {
        name: '意外身故/伤残',
        type: 'primary',
        description: '一般意外',
        coverageAmount: '100万',
        claimRatio: '100%',
      },
      {
        name: '公共交通意外',
        type: 'additional',
        description: '公交工具双倍赔',
        coverageAmount: '200万',
        claimRatio: '200%',
      },
    ],
    ageRange: { min: 18, max: 65 },
    healthRequirements: '无',
    coverageAmountRange: { min: 1000000, max: 1000000 },
    premiumStartFrom: 568,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://life.pingan.com/accident',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 8920,
    rating: 4.8,
    reviewCount: 5670,
    launchDate: '2024-02-20',
    updatedAt: '2024-10-28',
  },
  {
    id: 'product_025',
    name: '友邦安行无忧',
    companyId: 'company_003',
    companyName: '友邦保险',
    companyLogo: 'https://www.aia.com.cn/favicon.ico',
    category: 'accident',
    subCategory: '长期意外',
    description: '外资长期意外险，保至70岁，保费返还，港澳认可',
    highlights: [
      '保至70岁',
      '满期返保费',
      '港澳认可',
      '私家车双倍赔',
      '外资品质',
    ],
    coverageDetails: [
      {
        name: '意外身故/伤残',
        type: 'primary',
        description: '意外保障',
        coverageAmount: '50万',
        claimRatio: '100%',
      },
      {
        name: '满期生存金',
        type: 'additional',
        description: '70岁满期返还',
        coverageAmount: '已交保费',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 18, max: 60 },
    healthRequirements: '简单告知',
    coverageAmountRange: { min: 300000, max: 800000 },
    premiumStartFrom: 2680,
    paymentPeriods: ['10年交', '20年交'],
    coveragePeriods: ['至70岁'],
    purchaseUrl: 'https://www.aia.com.cn/accident',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 1890,
    rating: 4.9,
    reviewCount: 1230,
    launchDate: '2023-11-01',
    updatedAt: '2024-10-15',
  },
  {
    id: 'product_026',
    name: '阳光护身符',
    companyId: 'company_009',
    companyName: '阳光人寿',
    companyLogo: 'https://life.sinosig.com/favicon.ico',
    category: 'accident',
    subCategory: '综合意外',
    description: '互联网爆款意外险，性价比极高，含新冠保障',
    highlights: [
      '超高性价比',
      '含新冠保障',
      '在线秒投保',
      '3天无理由退',
      '全年仅99元起',
    ],
    coverageDetails: [
      {
        name: '意外身故/伤残',
        type: 'primary',
        description: '一般意外',
        coverageAmount: '30万',
        claimRatio: '100%',
      },
      {
        name: '意外医疗',
        type: 'primary',
        description: '意外医疗费用',
        coverageAmount: '3万',
        claimRatio: '100%（100元免赔）',
      },
    ],
    ageRange: { min: 18, max: 70 },
    healthRequirements: '无',
    coverageAmountRange: { min: 300000, max: 500000 },
    premiumStartFrom: 99,
    paymentPeriods: ['年交'],
    coveragePeriods: ['1年'],
    purchaseUrl: 'https://life.sinosig.com/accident',
    tags: ['high_value', 'fast_claim'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 23450,
    rating: 4.5,
    reviewCount: 15670,
    launchDate: '2024-01-10',
    updatedAt: '2024-11-08',
  },

  // ========== 寿险 (2个产品) ==========
  {
    id: 'product_027',
    name: '平安盛世长安',
    companyId: 'company_001',
    companyName: '平安人寿',
    companyLogo: 'https://www.chinalife.com.cn/favicon.ico',
    category: 'life',
    subCategory: '增额终身寿',
    description: '增额终身寿险，复利3.0%写入合同，支持减保，深圳专供版',
    highlights: [
      '复利3.0%增长',
      '写入合同',
      '支持减保',
      '现金价值高',
      '深圳专享',
    ],
    coverageDetails: [
      {
        name: '身故/全残',
        type: 'primary',
        description: '身故或全残给付',
        coverageAmount: '按现金价值',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 0, max: 70 },
    healthRequirements: '简单告知',
    coverageAmountRange: { min: 100000, max: 10000000 },
    premiumStartFrom: 100000,
    paymentPeriods: ['3年交', '5年交', '10年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://life.pingan.com/life-insurance',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth', 'chronic_disease'],
    salesStatus: 'active',
    monthSales: 2340,
    rating: 4.8,
    reviewCount: 1560,
    launchDate: '2023-10-15',
    updatedAt: '2024-11-01',
  },
  {
    id: 'product_028',
    name: '招商信诺传世壹号',
    companyId: 'company_002',
    companyName: '招商信诺',
    companyLogo: 'https://www.cignacmb.com/favicon.ico',
    category: 'life',
    subCategory: '定期寿险',
    description: '深圳本地定期寿险，保额高达千万，专为高净值家庭设计',
    highlights: [
      '最高千万保额',
      '保费低廉',
      '免责少',
      '深圳专供',
      '高净值家庭',
    ],
    coverageDetails: [
      {
        name: '身故/全残',
        type: 'primary',
        description: '身故或全残赔付',
        coverageAmount: '按基本保额',
        claimRatio: '100%',
      },
    ],
    ageRange: { min: 18, max: 60 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 500000, max: 10000000 },
    premiumStartFrom: 680,
    paymentPeriods: ['10年交', '20年交', '30年交'],
    coveragePeriods: ['至60岁', '至70岁'],
    purchaseUrl: 'https://www.cignacmb.com/life',
    tags: ['big_company', 'high_value'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 1120,
    rating: 4.7,
    reviewCount: 780,
    launchDate: '2024-02-01',
    updatedAt: '2024-10-25',
  },

  // ========== 长期护理险 (1个产品) ==========
  {
    id: 'product_029',
    name: '泰康爱家之约·护理计划',
    companyId: 'company_006',
    companyName: '泰康人寿',
    companyLogo: 'https://www.taikang.com/favicon.ico',
    category: 'long_term_care',
    subCategory: '长期护理',
    description: '失能护理保障，含居家护理，泰康之家粤园、鹏园优先入住',
    highlights: [
      '失能护理津贴',
      '居家护理服务',
      '养老社区对接',
      '广深专享',
      '终身保障',
    ],
    coverageDetails: [
      {
        name: '失能护理金',
        type: 'primary',
        description: '确定失能后按月给付',
        coverageAmount: '5000元/月',
        claimRatio: '终身给付',
        waitingPeriod: '180天',
      },
      {
        name: '居家护理服务',
        type: 'additional',
        description: '专业护理上门',
        coverageAmount: '每月2次',
        claimRatio: '免费',
      },
    ],
    ageRange: { min: 40, max: 70 },
    healthRequirements: '健康告知',
    coverageAmountRange: { min: 3000, max: 10000 },
    premiumStartFrom: 3680,
    paymentPeriods: ['10年交', '20年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.taikang.com/nursing',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', '60-70', 'all'],
    healthStatuses: ['standard', 'subhealth'],
    salesStatus: 'active',
    monthSales: 890,
    rating: 4.8,
    reviewCount: 560,
    launchDate: '2023-12-01',
    updatedAt: '2024-10-20',
  },

  // ========== 财富传承 (1个产品) ==========
  {
    id: 'product_030',
    name: '友邦传世荣耀',
    companyId: 'company_003',
    companyName: '友邦保险',
    companyLogo: 'https://www.aia.com.cn/favicon.ico',
    category: 'wealth_inheritance',
    subCategory: '大额寿险',
    description: '外资大额寿险，专为粤港澳高净值人士设计，含保险金信托',
    highlights: [
      '千万级保额',
      '保险金信托',
      '港澳认可',
      '税务筹划',
      '家族传承',
    ],
    coverageDetails: [
      {
        name: '身故保险金',
        type: 'primary',
        description: '身故给付',
        coverageAmount: '最高3000万',
        claimRatio: '100%',
      },
      {
        name: '保险金信托',
        type: 'additional',
        description: '信托架构设计',
        coverageAmount: '定制方案',
        claimRatio: '按信托条款',
      },
    ],
    ageRange: { min: 18, max: 65 },
    healthRequirements: '体检',
    coverageAmountRange: { min: 5000000, max: 30000000 },
    premiumStartFrom: 500000,
    paymentPeriods: ['趸交', '3年交', '5年交'],
    coveragePeriods: ['终身'],
    purchaseUrl: 'https://www.aia.com.cn/wealth',
    tags: ['big_company', 'specialized'],
    ageGroups: ['50-60', 'all'],
    healthStatuses: ['standard'],
    salesStatus: 'active',
    monthSales: 45,
    rating: 5.0,
    reviewCount: 28,
    launchDate: '2023-09-01',
    updatedAt: '2024-10-10',
  },
];

/**
 * 获取保险产品列表
 */
export const getProducts = async (filters?: {
  category?: InsuranceCategory | 'all';
  companyId?: string;
  ageGroup?: string;
  healthStatus?: string;
  sortBy?: string;
  page?: number;
  limit?: number;
}): Promise<{ data: InsuranceProduct[]; total: number; page: number; limit: number }> => {
  // 模拟网络延迟
  await new Promise(resolve => setTimeout(resolve, 500));

  let filteredProducts = [...mockProducts];

  // 类别筛选
  if (filters?.category && filters.category !== 'all') {
    filteredProducts = filteredProducts.filter(p => p.category === filters.category);
  }

  // 公司筛选
  if (filters?.companyId) {
    filteredProducts = filteredProducts.filter(p => p.companyId === filters.companyId);
  }

  // 年龄段筛选
  if (filters?.ageGroup && filters.ageGroup !== 'all') {
    filteredProducts = filteredProducts.filter(p =>
      p.ageGroups.includes(filters.ageGroup as any)
    );
  }

  // 健康状况筛选
  if (filters?.healthStatus) {
    filteredProducts = filteredProducts.filter(p =>
      p.healthStatuses.includes(filters.healthStatus as any)
    );
  }

  // 排序
  switch (filters?.sortBy) {
    case 'sales':
      filteredProducts.sort((a, b) => (b.monthSales || 0) - (a.monthSales || 0));
      break;
    case 'price_low':
      filteredProducts.sort((a, b) => a.premiumStartFrom - b.premiumStartFrom);
      break;
    case 'price_high':
      filteredProducts.sort((a, b) => b.premiumStartFrom - a.premiumStartFrom);
      break;
    case 'rating':
      filteredProducts.sort((a, b) => b.rating - a.rating);
      break;
    default:
      // 综合推荐：考虑评分和销量
      filteredProducts.sort((a, b) => {
        const scoreA = a.rating * 0.6 + (a.monthSales || 0) / 1000 * 0.4;
        const scoreB = b.rating * 0.6 + (b.monthSales || 0) / 1000 * 0.4;
        return scoreB - scoreA;
      });
  }

  // 分页
  const page = filters?.page || 1;
  const limit = filters?.limit || 10;
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedProducts = filteredProducts.slice(startIndex, endIndex);

  return {
    data: paginatedProducts,
    total: filteredProducts.length,
    page,
    limit,
  };
};

/**
 * 获取产品详情
 */
export const getProductById = async (productId: string): Promise<InsuranceProduct | null> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  return mockProducts.find(p => p.id === productId) || null;
};

/**
 * 按类别获取产品
 */
export const getProductsByCategory = async (
  category: InsuranceCategory
): Promise<InsuranceProduct[]> => {
  await new Promise(resolve => setTimeout(resolve, 400));
  return mockProducts.filter(p => p.category === category);
};

/**
 * 搜索产品
 */
export const searchProducts = async (keyword: string): Promise<InsuranceProduct[]> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  const lowerKeyword = keyword.toLowerCase();
  return mockProducts.filter(
    p =>
      p.name.toLowerCase().includes(lowerKeyword) ||
      p.description.toLowerCase().includes(lowerKeyword) ||
      p.companyName.toLowerCase().includes(lowerKeyword)
  );
};

/**
 * 产品对比
 */
export const compareProducts = async (productIds: string[]): Promise<InsuranceProduct[]> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  return mockProducts.filter(p => productIds.includes(p.id));
};

/**
 * 保费试算
 */
export const calculatePremium = async (
  productId: string,
  params: { age: number; gender: 'male' | 'female'; coverageAmount: number }
): Promise<{ annualPremium: number; monthlyPremium: number }> => {
  await new Promise(resolve => setTimeout(resolve, 400));

  const product = mockProducts.find(p => p.id === productId);
  if (!product) {
    throw new Error('Product not found');
  }

  // 简单的费率计算（实际应该根据产品费率表计算）
  const baseRate = product.premiumStartFrom;
  const ageFactor = 1 + (params.age - 30) * 0.02; // 年龄系数
  const genderFactor = params.gender === 'male' ? 1.1 : 1.0; // 性别系数
  const coverageFactor = params.coverageAmount / 100000; // 保额系数

  const annualPremium = Math.round(baseRate * ageFactor * genderFactor * coverageFactor);
  const monthlyPremium = Math.round(annualPremium / 12);

  return { annualPremium, monthlyPremium };
};

/**
 * 获取保险公司列表
 */
export const getInsuranceCompanies = async (): Promise<InsuranceCompany[]> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  return mockCompanies;
};

/**
 * 获取保险公司详情
 */
export const getCompanyById = async (companyId: string): Promise<InsuranceCompany | null> => {
  await new Promise(resolve => setTimeout(resolve, 200));
  return mockCompanies.find(c => c.id === companyId) || null;
};

/**
 * 记录用户意向产品
 */
export const trackProductInterest = async (
  userId: string,
  productId: string
): Promise<void> => {
  await new Promise(resolve => setTimeout(resolve, 200));
  console.log(`✅ 用户 ${userId} 对产品 ${productId} 感兴趣`);
  // 实际应该记录到后端
};
